## 读取数据

In [3]:
import pandas
df = pandas.read_csv('Data/house_data.csv')

## 检视前几行资料

In [4]:
df.head(3)

,Unnamed: 0,標題,产权性质,住宅类别,建筑类别,参考月供,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
0,0,急售70年产权房源 房东装修 户型正气 产证清晰 随时看房,个人产权,普通住宅,板楼,NaN,1989年,70.40,2室2厅1厨1卫,中层(共6层),暂无资料,住宅,平层,精装修,30.6
1,1,世纪大道站 福山外国语+建平西校 看房随时急卖,个人产权,普通住宅,塔楼,NaN,1989年,49.82,2室1厅0厨1卫,中层(共6层),1元/平米・月,住宅,平层,简装修,418.0
2,2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0

In [5]:
del df['Unnamed: 0']
df.head(3)

,標題,产权性质,住宅类别,建筑类别,参考月供,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
0,急售70年产权房源 房东装修 户型正气 产证清晰 随时看房,个人产权,普通住宅,板楼,NaN,1989年,70.40,2室2厅1厨1卫,中层(共6层),暂无资料,住宅,平层,精装修,30.6
1,世纪大道站 福山外国语+建平西校 看房随时急卖,个人产权,普通住宅,塔楼,NaN,1989年,49.82,2室1厅0厨1卫,中层(共6层),1元/平米・月,住宅,平层,简装修,418.0
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0

## 舍弃第一栏

In [7]:
df = pandas.read_csv('Data/house_data.csv',  index_col=0)

In [8]:
df.head(3)

,標題,产权性质,住宅类别,建筑类别,参考月供,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
0,急售70年产权房源 房东装修 户型正气 产证清晰 随时看房,个人产权,普通住宅,板楼,NaN,1989年,70.40,2室2厅1厨1卫,中层(共6层),暂无资料,住宅,平层,精装修,30.6
1,世纪大道站 福山外国语+建平西校 看房随时急卖,个人产权,普通住宅,塔楼,NaN,1989年,49.82,2室1厅0厨1卫,中层(共6层),1元/平米・月,住宅,平层,简装修,418.0
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0

## 将"暂无资料"变成缺失值

In [9]:
#df[df['物 业 费'] == '暂无资料']

In [10]:
import numpy as np
df.ix[df['物 业 费'] == '暂无资料', '物 业 费'] = np.nan
df.head(3)

/home/ziva/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

,標題,产权性质,住宅类别,建筑类别,参考月供,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
0,急售70年产权房源 房东装修 户型正气 产证清晰 随时看房,个人产权,普通住宅,板楼,NaN,1989年,70.40,2室2厅1厨1卫,中层(共6层),NaN,住宅,平层,精装修,30.6
1,世纪大道站 福山外国语+建平西校 看房随时急卖,个人产权,普通住宅,塔楼,NaN,1989年,49.82,2室1厅0厨1卫,中层(共6层),1元/平米・月,住宅,平层,简装修,418.0
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0

In [12]:
import pandas
df = pandas.read_csv('Data/house_data.csv', na_values='暂无资料',  index_col=0)
df.head(3)

,標題,产权性质,住宅类别,建筑类别,参考月供,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
0,急售70年产权房源 房东装修 户型正气 产证清晰 随时看房,个人产权,普通住宅,板楼,NaN,1989年,70.40,2室2厅1厨1卫,中层(共6层),NaN,住宅,平层,精装修,30.6
1,世纪大道站 福山外国语+建平西校 看房随时急卖,个人产权,普通住宅,塔楼,NaN,1989年,49.82,2室1厅0厨1卫,中层(共6层),1元/平米・月,住宅,平层,简装修,418.0
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0

## 检视后三行资料

In [13]:
df.tail(3)

,標題,产权性质,住宅类别,建筑类别,参考月供,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
237,6.12双轨，交通便利，配套成熟，购物方便，房东可接受置换！,个人产权,普通住宅,钢混,NaN,2005年,96.82,2室2厅1厨1卫,高层(共8层),1.86元/平米・月,住宅,平层,精装修,460.0
238,业主二次装修，保养好，户型方正，三房朝南，，随时看,个人产权,普通住宅,板楼,NaN,2002年,168.00,3室2厅1厨2卫,高层(共20层),2元/平米・月,住宅,平层,简装修,1250.0
239,区进门位置 三街坊43平直套通风一房 一梯二户 房东诚心卖,个人产权,普通住宅,板楼,NaN,1996年,43.13,1室1厅1厨1卫,高层(共7层),0.3元/平米・月,住宅,平层,简装修,278.0

## 检视DataFrame 信息

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 240 entries, 0 to 239
Data columns (total 14 columns):
標題       240 non-null object
产权性质     228 non-null object
住宅类别     218 non-null object
建筑类别     188 non-null object
参考月供     0 non-null float64
年代       224 non-null object
建筑面积     240 non-null float64
户型       240 non-null object
楼层       228 non-null object
物 业 费    215 non-null object
物业类型     240 non-null object
结构       181 non-null object
装修       228 non-null object
總價       237 non-null float64
dtypes: float64(3), object(11)
memory usage: 28.1+ KB

## 检视字段名称

In [15]:
df.columns

Index(['標題', '产权性质', '住宅类别', '建筑类别', '参考月供', '年代', '建筑面积', '户型', '楼层', '物 业 费',
       '物业类型', '结构', '装修', '總價'],
      dtype='object')

## 检视字段型态

In [16]:
df.dtypes

標題        object
产权性质      object
住宅类别      object
建筑类别      object
参考月供     float64
年代        object
建筑面积     float64
户型        object
楼层        object
物 业 费     object
物业类型      object
结构        object
装修        object
總價       float64
dtype: object

## 取得叙述性统计

In [17]:
df.describe()

       参考月供        建筑面积            總價
count   0.0  240.000000    237.000000
mean    NaN  113.435333    646.092869
std     NaN   99.199836   1300.349319
min     NaN   22.500000     30.600000
25%     NaN   68.952500    220.000000
50%     NaN   88.155000    400.000000
75%     NaN  123.250000    578.000000
max     NaN  731.240000  11000.000000

## 侦测缺失值

In [18]:
#df.isnull()

In [21]:
df.isnull().any()

標題       False
产权性质      True
住宅类别      True
建筑类别      True
参考月供      True
年代        True
建筑面积     False
户型       False
楼层        True
物 业 费     True
物业类型     False
结构        True
装修        True
總價        True
dtype: bool

In [22]:
df.isnull().sum()

標題         0
产权性质      12
住宅类别      22
建筑类别      52
参考月供     240
年代        16
建筑面积       0
户型         0
楼层        12
物 业 费     25
物业类型       0
结构        59
装修        12
總價         3
dtype: int64

In [474]:
df.isnull().sum() / df.count()

標題       0.000000
产权性质     0.052632
住宅类别     0.100917
建筑类别     0.276596
参考月供          inf
年代       0.071429
建筑面积     0.000000
户型       0.000000
楼层       0.052632
物 业 费    0.116279
物业类型     0.000000
结构       0.325967
装修       0.052632
總價       0.012658
dtype: float64

## 删除有缺失值的字段

In [524]:
df.head(3)

,標題,产权性质,住宅类别,建筑类别,参考月供,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
0,急售70年产权房源 房东装修 户型正气 产证清晰 随时看房,个人产权,普通住宅,板楼,NaN,1989年,70.40,2室2厅1厨1卫,中层(共6层),NaN,住宅,平层,精装修,30.6
1,世纪大道站 福山外国语+建平西校 看房随时急卖,个人产权,普通住宅,塔楼,NaN,1989年,49.82,2室1厅0厨1卫,中层(共6层),1元/平米・月,住宅,平层,简装修,418.0
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0

In [30]:
df = df.drop('参考月供', axis = 1)

In [526]:
df.head(3)

,標題,产权性质,住宅类别,建筑类别,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
0,急售70年产权房源 房东装修 户型正气 产证清晰 随时看房,个人产权,普通住宅,板楼,1989年,70.40,2室2厅1厨1卫,中层(共6层),NaN,住宅,平层,精装修,30.6
1,世纪大道站 福山外国语+建平西校 看房随时急卖,个人产权,普通住宅,塔楼,1989年,49.82,2室1厅0厨1卫,中层(共6层),1元/平米・月,住宅,平层,简装修,418.0
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0

## 筛选字段

In [477]:
df['产权性质'].value_counts()

个人产权     171
商品房       54
经济适用房      2
售后公房       1
Name: 产权性质, dtype: int64

In [530]:
#df[df['产权性质'] == '个人产权']

In [478]:
df[df['产权性质'] == '个人产权'].head(3)

,標題,产权性质,住宅类别,建筑类别,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
0,急售70年产权房源 房东装修 户型正气 产证清晰 随时看房,个人产权,普通住宅,板楼,1989年,70.40,2室2厅1厨1卫,中层(共6层),NaN,住宅,平层,精装修,30.6
1,世纪大道站 福山外国语+建平西校 看房随时急卖,个人产权,普通住宅,塔楼,1989年,49.82,2室1厅0厨1卫,中层(共6层),1元/平米・月,住宅,平层,简装修,418.0
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0

In [531]:
df.iloc[5:7]

,標題,产权性质,住宅类别,建筑类别,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
5,延吉控江一楼天井精装修水丰南北通透,商品房,NaN,板楼,1986年,35.0,1室2厅1厨1卫,低层(共6层),0.85元/平米・月,住宅,平层,简装修,205.0
6,纯双拼别墅，外环旁低总价，奢华大厅，美极了,NaN,NaN,NaN,NaN,237.0,4室3厅1厨4卫,NaN,3.8元/平米・月,别墅,NaN,NaN,1000.0

In [41]:
df.loc[(df['建筑面积'] > 100) & (df['總價'] > 2000) , ].head(1)

,標題,产权性质,住宅类别,建筑类别,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,2005年,288.3,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0

In [32]:
df.loc[df['建筑面积'] > 100].head(1)

,標題,产权性质,住宅类别,建筑类别,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,2005年,288.3,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0

In [33]:
df = df[df['产权性质'] == '个人产权']
df.head(3)

,標題,产权性质,住宅类别,建筑类别,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
0,急售70年产权房源 房东装修 户型正气 产证清晰 随时看房,个人产权,普通住宅,板楼,1989年,70.40,2室2厅1厨1卫,中层(共6层),NaN,住宅,平层,精装修,30.6
1,世纪大道站 福山外国语+建平西校 看房随时急卖,个人产权,普通住宅,塔楼,1989年,49.82,2室1厅0厨1卫,中层(共6层),1元/平米・月,住宅,平层,简装修,418.0
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0

In [34]:
df['产权性质'].value_counts()

个人产权    171
Name: 产权性质, dtype: int64

## 舍弃包含缺失值的字段

In [535]:
df.head(3)

,標題,产权性质,住宅类别,建筑类别,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
0,急售70年产权房源 房东装修 户型正气 产证清晰 随时看房,个人产权,普通住宅,板楼,1989年,70.40,2室2厅1厨1卫,中层(共6层),NaN,住宅,平层,精装修,30.6
1,世纪大道站 福山外国语+建平西校 看房随时急卖,个人产权,普通住宅,塔楼,1989年,49.82,2室1厅0厨1卫,中层(共6层),1元/平米・月,住宅,平层,简装修,418.0
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0

In [35]:
df[df['建筑类别'].isnull()].head(3)

,標題,产权性质,住宅类别,建筑类别,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0
12,月浦八村繁华地段 毗邻公园双南两房 双轨交通,个人产权,普通住宅,NaN,1991年,47.12,2室0厅0厨1卫,高层(共6层),0.6元/平米・月,住宅,NaN,中装修,180.0
27,投咨300亿山水六旗主题公园 金色海岸 海景房 得房率110,个人产权,普通住宅,NaN,2016年,84.00,2室2厅0厨1卫,中层(共15层),NaN,住宅,NaN,毛坯,80.0

In [536]:
df = df.dropna(axis=1, how='all')

In [537]:
df.head(3)

,標題,产权性质,住宅类别,建筑类别,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
0,急售70年产权房源 房东装修 户型正气 产证清晰 随时看房,个人产权,普通住宅,板楼,1989年,70.40,2室2厅1厨1卫,中层(共6层),NaN,住宅,平层,精装修,30.6
1,世纪大道站 福山外国语+建平西校 看房随时急卖,个人产权,普通住宅,塔楼,1989年,49.82,2室1厅0厨1卫,中层(共6层),1元/平米・月,住宅,平层,简装修,418.0
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0

## 补齐缺失值

In [538]:
df.head(3)

,標題,产权性质,住宅类别,建筑类别,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
0,急售70年产权房源 房东装修 户型正气 产证清晰 随时看房,个人产权,普通住宅,板楼,1989年,70.40,2室2厅1厨1卫,中层(共6层),NaN,住宅,平层,精装修,30.6
1,世纪大道站 福山外国语+建平西校 看房随时急卖,个人产权,普通住宅,塔楼,1989年,49.82,2室1厅0厨1卫,中层(共6层),1元/平米・月,住宅,平层,简装修,418.0
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0

In [36]:
df['物 业 费'] =df['物 业 费'].fillna(0)

In [37]:
df.head(3)

,標題,产权性质,住宅类别,建筑类别,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
0,急售70年产权房源 房东装修 户型正气 产证清晰 随时看房,个人产权,普通住宅,板楼,1989年,70.40,2室2厅1厨1卫,中层(共6层),0,住宅,平层,精装修,30.6
1,世纪大道站 福山外国语+建平西校 看房随时急卖,个人产权,普通住宅,塔楼,1989年,49.82,2室1厅0厨1卫,中层(共6层),1元/平米・月,住宅,平层,简装修,418.0
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0

In [38]:
df['總價'].isnull().sum()

2

In [39]:
df[df['總價'].isnull()]

,標題,产权性质,住宅类别,建筑类别,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
18,光新路191弄 南北通透两室户 地段佳 出行方便满五少税,个人产权,普通住宅,板楼,1990年,47.00,2室1厅1厨1卫,低层(共6层),0.3元/平米・月,住宅,平层,精装修,NaN
175,精品好房 稍纵即逝,个人产权,普通住宅,钢混,2014年,99.38,3室2厅1厨2卫,中层(共11层),1.95元/・月,住宅,平层,精装修,NaN

In [545]:
(df['總價'] / df['建筑面积']).mean()

4.5302593877717445

In [489]:
df['總價'].isnull().sum()

2

In [546]:
df['總價'] = df['總價'].fillna(df['建筑面积'] * (df['總價'] / df['建筑面积']).mean())

In [547]:
df['總價'].isnull().sum()

0

In [548]:
df.head()

,標題,产权性质,住宅类别,建筑类别,年代,建筑面积,户型,楼层,物 业 费,物业类型,结构,装修,總價
0,急售70年产权房源 房东装修 户型正气 产证清晰 随时看房,个人产权,普通住宅,板楼,1989年,70.40,2室2厅1厨1卫,中层(共6层),0,住宅,平层,精装修,30.6
1,世纪大道站 福山外国语+建平西校 看房随时急卖,个人产权,普通住宅,塔楼,1989年,49.82,2室1厅0厨1卫,中层(共6层),1元/平米・月,住宅,平层,简装修,418.0
2,大四房出售，带会所+高区景观+车位,个人产权,普通住宅,NaN,2005年,288.30,4室2厅0厨2卫,高层(共40层),3.5元/平米・月,住宅,NaN,精装修,2650.0
4,"满五税费少,房东接受置换客户,房东这边房子已经看好,急卖",个人产权,普通住宅,钢混,1998年,58.00,2室1厅1厨1卫,高层(共6层),0.4元/平米・月,住宅,平层,精装修,190.0
7,纪联小区，，大一房一厅，精装修，，！诚售,个人产权,普通住宅,板楼,1996年,50.00,1室1厅1厨1卫,中层(共6层),0,住宅,平层,精装修,230.0

## 将资料写入CSV 中

In [549]:
df.to_csv('house_final.csv', index_label=False)